// Variables
a = 10;
b = 20;
c = a + b()(a());

smth.method(vararg=2, "arg");

a ^^= true;

// Functions
d = fn(a, b) { return a + b; }; // Lambda
d = fn(a, b) = a + b;

fn e(a, b) {
    return a + b;
}

// Conditions
if (a == 1) { print(i); }
if (a == 1) print(i);
if a == 1 { print(i); }
if a == 1 print(i);

// Loops
for (i in a) { print(i); }
for i in a { print(i); }
while (i) { print(i); }
while i { print(i); }
do { print(i); } while (i);
do { print(i); } while i;